# Generated by Django 4.1.6 on 2023-04-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enlistment', '0002_student_password_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='password_hash',
            new_name='password',
        ),
    ]
